name: 'MkDocs configuration builder'
description: 'Builds a YAML configuration file for MkDocs'
author: 'Simonas Bunevicius'
inputs:
  siteName:
    required: true
    description: 'value on for site_name key'
  docsFolder:
    required: true
    description: 'directory where documentation is placed'
  outputDirectory:
    required: false
    description: 'directory where mkdocs will be placed'
  docsFolder:
    required: false
    description: 'value on for docs_dir key'
runs:
  using: 'node12'
  main: 'dist/index.js'
