name: 'MkDocs configuration builder'
description: 'Builds a YAML configuration file for MkDocs'
author: 'Simonas Bunevicius'
inputs:
  siteName:
    required: true
    description: 'value on for site_name key'
  docsFolder:
    required: true
    description: 'directory where documentation is placed'
  outputPath:
    required: true
    description: 'directory where generated file will place'
    default: 'mkdocs.yml'

runs:
  using: 'node12'
  main: 'dist/index.js'
